POST /oauth2/v4/token HTTP/1.1
Host: www.googleapis.com
Content-length: 223
content-type: application/x-www-form-urlencoded
user-agent: google-oauth-playground

client_secret=************
&grant_type=refresh_token
&refresh_token=1%2F%2F04Pg27pB-rblCCgYIARAAGAQSNwF-L9IrcWQFO5wI2hkwf-pT0-f_o1nmk71jF8pywXl0Y8G45FhEIJIdQsjsjqhjTNYLlBBkzmE
&client_id=407408718192.apps.googleusercontent.com

client_id=258221848721-kn14pr7avkenqrqp9agcg85g6pk34t3h.apps.googleusercontent.com
&client_secret=d2C7t1_cbD9vuIHePNwQmYY5
&redirect_uri=https%3A%2F%2Fcustomeapp-dev-ed.my.salesforce.com%2Flightning%2Fcmp%2Fc__TreeGoogleDriveConnect
&grant_type=refresh_token
&refresh_token=1%2F%2F04Pg27pB-rblCCgYIARAAGAQSNwF-L9IrcWQFO5wI2hkwf-pT0-f_o1nmk71jF8pywXl0Y8G45FhEIJIdQsjsjqhjTNYLlBBkzmE


String messageBody = '&client_id='+key+'&client_secret='+secret+'&redirect_uri='+redirect_uri+'&grant_type=refresh_token'+'&refresh_token'+refresh_token; 



client_secret=************
&grant_type=refresh_token
&refresh_token=1%2F%2F04Pg27pB-rblCCgYIARAAGAQSNwF-L9IrcWQFO5wI2hkwf-pT0-f_o1nmk71jF8pywXl0Y8G45FhEIJIdQsjsjqhjTNYLlBBkzmE
&client_id=407408718192.apps.googleusercontent.com